{% set name = "dagster_datadog" %}
{% set version = "0.6.7.post0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name|replace('_', '-') }}/{{ name|replace('_', '-') }}-{{ version }}.tar.gz"
  sha256: 191ccc30b817ee460eb092911a24a0edb104567764ab50d5aa63edeacf904624

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - dagster {{ version }}.*
    - datadog

test:
  imports:
    - dagster_datadog

about:
  home: "https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-datadog"
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "Package for datadog Dagster framework components."

extra:
  recipe-maintainers:
    - conda-forge/dagster
